// <auto-generated />
namespace ClothBazar.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_NAmeAddress_to_IdentityModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_NAmeAddress_to_IdentityModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311647177_added_NAmeAddress_to_IdentityModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
