// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BaseInsurance_Gender_Frequency_INsuranceProducts_ULIPS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseInsurance_Gender_Frequency_INsuranceProducts_ULIPS));
        
        string IMigrationMetadata.Id
        {
            get { return "202202041248340_BaseInsurance_Gender_Frequency_INsuranceProducts_ULIPS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
