// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addded_ORder_OrderItems_Entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addded_ORder_OrderItems_Entities));
        
        string IMigrationMetadata.Id
        {
            get { return "202202010509378_addded_ORder_OrderItems_Entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
