// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_configclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_configclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202201220821069_added_configclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
