// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_Quantity_in_OrderItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Quantity_in_OrderItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202202010607142_added_Quantity_in_OrderItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
