// <auto-generated />
namespace ClothBazar.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedBaseValidations_Price_in_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedBaseValidations_Price_in_product));
        
        string IMigrationMetadata.Id
        {
            get { return "202201261628338_addedBaseValidations_Price_in_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
